# The time format of the data.
data_time_format: "%Y-%m-%d %H:%M:%S"

time_attribute_name: time
longitude_attribute_name: longitude
latitude_attribute_name: latitude
elevation_attribute_name: elevation

# The unit must be one of 'km' and 'm'.
elevation_unit: m

# dtype of the data and weight.
dtype: float32