#  This file uses ## and # to mark optional parameters and normal comments 
# respectively.

# The mode of association layer.
# If the mode is not null, using dict to set the association mode.
# The key is the name of the mode, and the value is the number of channels.
# If the value of the mode is null, the channel will set to default.
association mode: null
#  If the mode is GC, the value means the number of channels to add to the 
# input. Default to 1.
## association mode: GC: 1
#  If the mode is GCN, the value means the number of output channels.
# Default to the number of input channels.
## association mode: GCN: null
#  If the mode is GAT or INA, the value means the number of hidden channels.
# Default to 32.
## association mode: GAT: 32
# association mode: INA: 32

# The threshold of adjacency matrix.
# Must be set when association mode is GC, GCN or GAT.
adjacency threshold: 200km

# The mode of RNNs.
# The key is the name of the mode, and the value is the number of hidden units.
RNN mode: RNN: 64
## RNN mode: LSTM: 64
## RNN mode: GRU: 64

# The time steps of RNN.
input time steps: 24

# The interval between end of input and start of prediction.
predict interval: 1

# The number of time steps to be predicted.
predict time steps: 8