# The cities to be predicted in the model evaluation.
prediction_cities:
    # 2 Municipalities.
    - Beijing
    - Tianjin
    # 26 cities.
    - Anyang 
    - Baoding
    - Binzhou
    - Cangzhou
    - Changzhi
    - Dezhou
    - Handan
    - Hebi
    - Hengshui
    - Heze
    - Jiaozuo
    - Jinan
    - Jincheng
    - Jining
    - Kaifeng
    - Langfang
    - Liaocheng
    - Puyang
    - Shijiazhuang
    - Taiyuan
    - Tangshan
    - Xingtai
    - Xinxiang
    - Yangquan
    - Zhengzhou
    - Zibo

# Pollutants attributes with their concentration factor.
pollutants_attributes:
    CO: 1.0
    NO2: 1.0
    O3: 1.0
    PM10: 1.0
    PM2.5: 1.0
    SO2: 1.0
